### ISSUE TITLE
gestionar

### ISSUE THREAD

**Issue by lmagarin** [pxblx/programacionJava#13]
https://github.com/pxblx/programacionJava/blob/d77299abaaf013f677a0914933f528a25458d447/practicas/poo3/gestisimal/TestAlmacen.java#L32

Debe devolver una opción válida. Si no  estáis dejando que otro haga el trabajo de menú

**Comment by pxblx** [comment]
Devuelve una opción válida o lanza una excepción:
https://github.com/pxblx/programacionJava/blob/d77299abaaf013f677a0914933f528a25458d447/practicas/poo3/gestisimal/src/utiles/Menu.java#L46

Pero en el test al saltar la excepción pongo la variable a 0 para que pase por el break del switch y vuelva a mostrarse el menú:
https://github.com/pxblx/programacionJava/blob/d77299abaaf013f677a0914933f528a25458d447/practicas/poo3/gestisimal/TestAlmacen.java#L102

**Comment by lmagarin** [comment]
Cierto, pero... ¿por qué excepciones? Creo que abusas.
¿Qué problema hay en dejarlo todo en Menú? Para eso está la clase.
Si el método pedirOpción ya sabe que la opción NO es válida, ¿qué necesidad tienes de mandar el error fuera?
Con la clase menú se pretende que su usuario:
- Muestre opciones 
- Recoja opciones VÁLIDAS
y se quite de problemas cuando la entrada por teclado no sea válida.
```
	/**
	 * Devuelve una opción válida del menú introducida por el teclado. En caso de no
	 * ser válida se solicita de nuevo.
	 * 
	 * @return opción válida
	 */
	private int getOpcionValida() {
		int opcion;
		do {
			System.out.println("Elige opción [1, " + NUM_OPCIONES + "]");
			opcion = Teclado.getEntero();
		} while (!esOpcionValida(opcion));
		setOpcionElegida(opcion);
		return opcion;

	}

	/**
	 * Indica si la opción es válida
	 * 
	 * @param opcion número a comparar
	 * @return true si es válida. false en otro caso
	 */
	private boolean esOpcionValida(int opcion) {
		return (opcion >= 1 && opcion <= NUM_OPCIONES);
	}

```
