### ISSUE TITLE
Extraed métodos en cada case

### ISSUE THREAD

**Issue by lmagarin** [pxblx/programacionJava#9]
https://github.com/pxblx/programacionJava/blob/7b134b4602504df8185befa0323806f1c0bde447/practicas/poo3/gestisimal/test/TestAlmacen.java#L42

**Comment by lmagarin** [comment]
¿No habéis extraído  los métodos?

**Comment by JSillero** [comment]
Por extraer metodo te refieres a que en cada opcion todo el codigo que rodea a la funcion , por ejemplo

try {
            descripcion = Teclado.leerCadena("\nIntroduce la descripción del artículo: ");
            precioCompra = Teclado.leerDecimal("Introduce el precio de compra del artículo: ");
            precioVenta = Teclado.leerDecimal("Introduce el precio de venta del artículo: ");
            unidades = Teclado.leerEntero("Introduce el número de unidades del artículo: ");
          } catch (NumberFormatException e) {
            System.err.println("\nEntrada de datos incorrecta.\n");
            break;
          }
          try {
            almacen.altaArticulo(descripcion, precioCompra, precioVenta, unidades);
            System.out.print("Artículo creado.\n\n");
          } catch (ExcepcionDescripcionVacia e) {
            System.err.println("\n" + e.getMessage() + "\n");
          } catch (ExcepcionValorNegativo e) {
            System.err.println("\n" + e.getMessage() + "\n");
          } catch (ExcepcionArticuloExistente e) {
            System.err.println("\n" + e.getMessage() + "\n");
          }
          break;

se metiese ese codigo dentro del metodo llamado para que solo quedase 

  almacen.altaArticulo(descripcion, precioCompra, precioVenta, unidades);
